# Generated by Django 4.1.7 on 2024-03-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applyform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('position', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('cover_letter', models.CharField(max_length=150)),
                ('resume', models.FileField(upload_to='Files')),
            ],
        ),
    ]
